# Read the Docs Configuration File
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required: The version of the configuration file format.
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  # 指向 conf.py 的路径，相对于仓库根目录
  configuration: docs/source/conf.py
  builder: build/html
  # Optional: Specify the build directory if not the default _build/html
  # build_html_dir: _build/html # 这个通常由 Makefile 处理，且默认就是 _build/html

# Build environment configuration
build:
  os: ubuntu-latest
  tools:
    python: "3.9" # 使用一个稳定的 Python 版本

# Install project dependencies including Sphinx and theme
python:
  install:
    # 假设所有文档和项目依赖仍然在仓库根目录的 requirements.txt 文件中
    - requirements: requirements.txt
    # 如果您的文档依赖在 docs/requirements.txt，则使用：
    # - requirements: docs/requirements.txt
    # 如果您的文档依赖在 docs/source/requirements.txt，则使用：
    # - requirements: docs/source/requirements.txt
    # 如果您的文档需要导入项目本身的模块：
    # - method: pip
    #   path: . # 相对于仓库根目录安装项目

# Optional: If your source files are all under docs/source/ and you want to be explicit
# Although sphinx.configuration usually suffices
# formats: [] # Prevent building PDF/ePub