openai:
  # api_key: "sk-proj-VDIJaYm4FHdllkYfdh-2LKKyzbbnfGAA"
  model: "gpt-3.5-turbo" # gpt-3.5-turbo, gpt-4
  timeout: 30
  max_retries: 3
  max_history: 8  # 保留最近8轮对话

deepseek:
  # api_key: "sk-db9e899099c4429fhtjshg490e240d3ce143"
  base_url: "https://api.deepseek.com"
  model: "deepseek-reasoner" # deepseek-chat
  timeout: 300
  max_retries: 10
  max_history: 8  # 保留最近8轮对话

gemini:
  # api_key: "AIzaSyAqbHWOgqe9eMHuFZfhk8fonsB2BgKyfeSR0c"
  model: "gemini-1.5-pro"
  timeout: 300
  max_retries: 10
  max_history: 6  # Gemini建议较短的对话历史

grok:
  # api_key: "xai-wzc9pE5gJGdA9W9C9rkIaw8Q5SGLa4bJIliB2H"
  base_url: "https://api.x.ai/v1"
  model: "grok-2-latest" # 
  timeout: 300
  max_retries: 10
  max_history: 8  # 保留最近8轮对话
